# Generated by Django 2.2.10 on 2021-05-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Middlename', models.CharField(blank=True, max_length=100)),
                ('LastName', models.CharField(blank=True, max_length=100)),
                ('Email', models.CharField(blank=True, max_length=100)),
                ('PhoneNumber', models.CharField(blank=True, max_length=100)),
                ('IdNumber', models.ImageField(upload_to='images/%Y/%M/%D/')),
                ('PassPort', models.ImageField(upload_to='images/%Y/%M/%D/')),
                ('Certificate', models.ImageField(upload_to='images/%Y/%M/%D/')),
                ('School', models.CharField(blank=True, max_length=100)),
                ('Country', models.CharField(blank=True, max_length=100)),
                ('Gender', models.CharField(blank=True, max_length=100)),
                ('Language', models.CharField(blank=True, max_length=100)),
                ('WorkExperience', models.CharField(blank=True, max_length=100)),
                ('City', models.CharField(blank=True, max_length=100)),
                ('Address', models.CharField(blank=True, max_length=100)),
                ('NightCalls', models.CharField(blank=True, max_length=100)),
                ('ForceAssignments', models.CharField(blank=True, max_length=100)),
                ('SocialMedia', models.CharField(blank=True, max_length=100)),
                ('AdditionalInfo', models.CharField(blank=True, max_length=5000)),
                ('LevelOfEducation', models.CharField(blank=True, max_length=100)),
                ('Status', models.CharField(blank=True, max_length=100)),
                ('AccountType', models.CharField(blank=True, max_length=100)),
                ('QualityCheckPoints', models.CharField(blank=True, max_length=100)),
                ('DurationPoints', models.CharField(blank=True, max_length=100)),
                ('DisputePoints', models.CharField(blank=True, max_length=100)),
                ('RequestPoints', models.CharField(blank=True, max_length=100)),
                ('LatenessPoints', models.CharField(blank=True, max_length=100)),
                ('Score', models.CharField(blank=True, max_length=100)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
            ],
        ),
    ]
