# Generated by Django 2.2.10 on 2021-05-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writters',
            name='Level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='writters',
            name='QualityOfWork',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
