# Generated by Django 2.2.10 on 2021-03-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePerDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration', models.CharField(choices=[('1 Month', '1 Month'), ('14 Days', '14 Days'), ('7 Days', '7 Days'), ('5 Days', '5 Days'), ('3 Days', '3 Days'), ('2 Days', '2 Days'), ('24 Hours', '24 Hours'), ('8 Hours', '8 Hours'), ('4 Hours', '4 Hours')], default='14 Days', max_length=50)),
                ('Level', models.CharField(choices=[('High School', 'High School'), ('Undergraduate(1-2Yrs)', 'Undergraduate(1-2Yrs)'), ('Undergraduate(3-4Yrs)', 'Undergraduate(3-4Yrs)'), ('Graduate', 'Graduate'), ('PHD', 'PHD')], default='Undergraduate(1-2Yrs)', max_length=50)),
                ('Amount', models.CharField(blank=True, max_length=100)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
            ],
        ),
    ]
