# Generated by Django 2.2.10 on 2021-04-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_discipline_typepaper_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='DisciplineType',
            field=models.CharField(choices=[('All', 'All'), ('Tiny', 'Tiny'), ('Hard', 'Hard')], default='Al', max_length=50),
        ),
        migrations.AddField(
            model_name='typepaper',
            name='PaperType',
            field=models.CharField(choices=[('Essay', 'Essay'), ('Hard Type', 'Hard Type'), ('Massive Type', 'Massive Type')], default='Essay', max_length=50),
        ),
    ]
