# Generated by Django 2.2.10 on 2021-04-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20210403_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('TypeOfPaper', models.CharField(max_length=100)),
                ('Discipline', models.CharField(blank=True, max_length=100)),
                ('ipaddress', models.CharField(blank=True, max_length=100)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='discipline',
            name='DisciplineType',
            field=models.CharField(choices=[('All', 'All'), ('Tiny', 'Tiny'), ('Hard', 'Hard')], default='All', max_length=50),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='Status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='typepaper',
            name='Status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
    ]
