# Generated by Django 2.2.10 on 2021-04-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20210403_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='temppaper',
            name='AcademicLevel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temppaper',
            name='PaperFormat',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
