# Generated by Django 2.2.10 on 2021-04-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20210403_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='temppaper',
            name='Timeline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
