# Generated by Django 2.2.10 on 2021-04-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_temppaper_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='temppaper',
            name='Charts',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temppaper',
            name='Pages',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temppaper',
            name='Slides',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temppaper',
            name='Slidesources',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temppaper',
            name='Sources',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temppaper',
            name='Spacing',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
