# Generated by Django 2.2.10 on 2021-04-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='FileName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
