# Generated by Django 2.2.10 on 2021-04-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_documents_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='temppaper',
            name='Description',
            field=models.CharField(blank=True, max_length=30000),
        ),
    ]
