# Generated by Django 2.2.10 on 2021-04-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_temppaper_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperSumation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(max_length=100)),
                ('Description', models.CharField(blank=True, max_length=100)),
                ('Amount', models.CharField(blank=True, max_length=100)),
                ('Status', models.CharField(blank=True, max_length=100)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
            ],
        ),
    ]
