# Generated by Django 2.2.10 on 2021-04-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_papersumation'),
    ]

    operations = [
        migrations.AddField(
            model_name='temppaper',
            name='Copysources',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temppaper',
            name='NativeSpeaker',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temppaper',
            name='Progressivedelivery',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temppaper',
            name='SmartPaper',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temppaper',
            name='Writersample',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
