# Generated by Django 2.2.10 on 2021-04-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_auto_20210410_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='temppaper',
            name='Amount',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temppaper',
            name='OrderStatus',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temppaper',
            name='Orderid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temppaper',
            name='PaymentStatus',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
