# Generated by Django 2.2.10 on 2021-04-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_auto_20210410_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='temppaper',
            name='UserId',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
