# Generated by Django 2.2.10 on 2021-05-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_temppaper_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='temppaper',
            name='BidOption',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
