# Generated by Django 2.2.10 on 2021-05-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_auto_20210504_0528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temppaper',
            old_name='CPP',
            new_name='CPPENL',
        ),
        migrations.AddField(
            model_name='temppaper',
            name='CPPESL',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
