# Generated by Django 2.2.10 on 2021-05-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_auto_20210504_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaperId', models.CharField(max_length=100)),
                ('Message', models.CharField(blank=True, max_length=1000)),
                ('From', models.CharField(blank=True, max_length=100)),
                ('Status', models.CharField(blank=True, max_length=100)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
            ],
        ),
    ]
