# Generated by Django 2.2.10 on 2021-05-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_papermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='temppaper',
            name='Writter',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
