# Generated by Django 2.2.10 on 2021-05-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_temppaper_writter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperBids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaperId', models.CharField(max_length=100)),
                ('Title', models.CharField(blank=True, max_length=1000)),
                ('Discipline', models.CharField(blank=True, max_length=100)),
                ('Writter', models.CharField(blank=True, max_length=100)),
                ('WritterId', models.CharField(blank=True, max_length=100)),
                ('Status', models.CharField(blank=True, max_length=100)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
            ],
        ),
    ]
