# Generated by Django 2.2.10 on 2021-05-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_paperbids'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperbids',
            name='Bid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
