# Generated by Django 2.2.10 on 2021-05-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0023_paperbids_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='temppaper',
            name='DisputeMain',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='temppaper',
            name='Disputereason',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
