# Generated by Django 2.2.10 on 2021-05-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0024_auto_20210517_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='Grad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='discipline',
            name='Highschool',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='discipline',
            name='PHD',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='discipline',
            name='Undergrad1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='discipline',
            name='Undergrad2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='typepaper',
            name='Grad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='typepaper',
            name='Highschool',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='typepaper',
            name='PHD',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='typepaper',
            name='Undergrad1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='typepaper',
            name='Undergrad2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
