# Generated by Django 2.2.10 on 2021-05-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0025_auto_20210528_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='Description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
