# Generated by Django 3.1.5 on 2021-06-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0026_documents_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=10000)),
                ('message', models.TextField(blank=True, max_length=100000)),
            ],
        ),
    ]
