# Generated by Django 3.1.5 on 2021-06-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0027_messages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AddField(
            model_name='messages',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
